version: "3"
services:
  app:
    image: latiendadelbebe
    container_name: latiendadelbebe
    restart: always
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - upload:/app/public/upload
      - data:/app/data
volumes:
  upload:
  data: